<?php
/**
 * @file
 * RSVP Module hooks.
 */
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Database\Database;

/**
* Implements hook_preprocess_node().
*
* Alter the node templete to include the list of attendees.
*/
function rsvplist_preprocess_node(&$variables) {

  $node = $variables['node'];

  if ($node->bundle() == 'event') {
    $nid = $node->id();
    $select = Database::getConnection()->select('rsvplist', 'r');
    $select->addField('r', 'name');
    $select->condition('attendee_list_hidden', 0);
    $select->condition('nid', $nid);
    $entries = $select->execute()->fetchAll(\PDO::FETCH_ASSOC);

    $content['#weight'] = 200;
    $content['message'] = array(
      '#markup' => t('Below is a list of attendees on this event.'),
    );
    $headers = array(
      t('Name'),
    );
    $rows = array();
    foreach ($entries as $entry) {
      // Sanitize each entry.
      $rows[] = array_map('Drupal\Component\Utility\SafeMarkup::checkPlain', $entry);
    }
    $content['table'] = array(
      '#type' => 'table',
      '#header' => $headers,
      '#rows' => $rows,
      '#empty' => t('No entries available.'),
    );
    $variables['content']['list_of_attendess'] = $content;
  }

}

/**
 * Implements HOOK_preprocess_block() for block templates.
 */
function rsvplist_preprocess_block( array &$variables) {
  $block_id = $variables['elements']['#id'];

  /* Add classes based on the block id. */
  switch ($block_id) {
    /* RSVP Menu block */
    case 'rsvpblock':
      $variables['attributes']['class'][] =  'hidden';
      break;
  }
}
